### PR TITLE
Show resource's group/version/kind when validation fails

### PR DESCRIPTION
**Pull request by hgontijo**
Show resource's group/version/kind when it's not available on the Kubernetes cluster.

### CODE REVIEW

**Comment by hgontijo** [comment]
One scenario this is useful is when the user is bringing CRDs to the cluster and dependencies are not configured between CRD and resource. Once the resources are being created or deleted, there could be a race condition between CRD and actual resource.

**Comment by gavinbunney** [comment]
👏

**Comment by hgontijo** [comment]
Thanks, can we have a new release? 🙏 😄

**Comment by gavinbunney** [comment]
Published! https://github.com/gavinbunney/terraform-provider-kubectl/releases/tag/v1.0.1

**Pull request merged**
