### PR TITLE
fix: Introduces wait polling in case we are waiting for the deletion.…

### PR DESCRIPTION
**Pull request by alekc**
Introduces wait for deletion polling.

Fixes https://github.com/gavinbunney/terraform-provider-kubectl/issues/109

### CODE REVIEW

**Comment by alekc** [comment]
It looks like kubectl provider does the right job by setting a proper propagation policy,  the issue is that we are not waiting for resource to be deleted. 

This patch introduce polling operation, in case there is a wait flag, it will poll upstream and wait for deletion of the object indefinitely (until default TF timeout kicks in)

I am having a bit of an issue with the test though, because i am not sure that we can change timeout dynamically?
this is my attempt
```
func TestKubectlManifest_WaitForFinalizer(t *testing.T) {
	t.Parallel()
	cmName := "dev-cm-" + acctest.RandString(10)

	// language=HCL
	config := fmt.Sprintf(`
resource "kubectl_manifest" "test" {
	wait = true
	yaml_body = <<YAML
apiVersion: v1
kind: ConfigMap
metadata:
  finalizers:
  - fake.com/finalizer
  name: %s
YAML
}
	`, cmName)

	resource.Test(t, resource.TestCase{
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			// create CM
			{
				Config: config,
			},
			// try to destroy it, we should get an error
			{
				Config:  config,
				Destroy: true,
			},
		},
	})
}
```
@gavinbunney

**Comment by patst** [comment]
@gavinbunney sorry to bug you too. Would be great to get some feedback if there is the chance to get this merged or if there should be some adjustment to the code.

**Comment by gavinbunney** [comment]
Thanks LGTM!

**Comment by stevehipwell** [comment]
@gavinbunney could you cut a release so this can be used?

**Comment by valorl** [comment]
@gavinbunney sorry for the ping, but I'm hoping making a release isn't too much effort. This could really unblock things for me.

**Pull request merged**
